profiles:
  active: LOCAL
spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  #      use_sql_comments: true
#  mvc:
#    #    throw-exception-if-no-handler-found: true
#    static-path-pattern: /resources/**

logging:
  #  file: logs
  #  config: classpath:log/logback-spring.xml
  level:
    com.syshology.jpa: info
    org:
      hibernate:
        SQL: info
        type:
          descriptor: info
#      com.zaxxer.hikari.HikariDataSource: trace


